![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [14]:
import numpy as np 
np.__version__

'2.1.2'

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [18]:

my_array=[0,1,2,3,4,5,6,7,8,9]
my_array
my_array= np.arange(0,10)

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [19]:
array_3x3 = np.array([ 
     [True, True, True],
     [ True, True, True], 
     [True, True, True] 

     ])

array_3x3



array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
import numpy as np
array= np.full((3,3), True)
print(array)


[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


## Ejercicio 4
Extrae todos los impares de `my_array`

In [20]:
my_array = [0,1,2,3,4,5,6,7,8,9]
lista2= []

for elemento in my_array:
    if elemento % 2 != 0:
        lista2.append(elemento)
    

print(lista2 )    



[1, 3, 5, 7, 9]


In [ ]:
my_array = [0,1,2,3,4,5,6,7,8,9]
mask = my_array%2 != 0



## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [44]:

my_array = np.array([0,1,2,3,4,5,6,7,8,9])
nuevo_elemento = -1 
for clave, valor in enumerate(my_array): #clave es el indice, valor es el numero
    if valor %2 !=0:
        my_array[clave] = nuevo_elemento

print(my_array)       
    




[ 0 -1  2 -1  4 -1  6 -1  8 -1]


## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [57]:

my_array = np.array([0,1,2,3,4,5,6,7,8,9])
#np.where(condición, valor_si_verdadero, valor_si_falso)
my_array = np.where(my_array %2!= 0, -1, my_array )
my_array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [70]:

# Usas np.array() para convertir la lista en un array, usa datos q ya tengo 
lista = [1, 2, 3, 4, 5]
array_1 = np.array(lista)
print(array_1)
#Usas np.arange() para crear una secuencia de números del 0 al 8
array_rango = np.arange(9)
print(array_rango)


[1 2 3 4 5]
[0 1 2 3 4 5 6 7 8]


## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [75]:
my_array = np.array([0,1,2,3,4,5,6,7,8,9]) #10 elementos por lo q el nuevo sera cualquier combinacion q de 10 5x2, 2x5 
nuevo_array = my_array.reshape(2,5) 
print(nuevo_array)
nuevo_array1 = my_array.reshape(2,-1) 
print(nuevo_array1) #el -1 es si no sabes el tañamno de una de las dimesnsiones y lo calcula solo

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1 2 3 4]
 [5 6 7 8 9]]


## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1) #numero del 0 al 9, y lo transformamos en matrix bidimensiolan 2 filas y columnas ?
b = np.repeat(1, 10).reshape(2,-1)  #repite el valor 1 10 veces, y est se reorganiza en 2 filas y 5 columnas 
```

In [87]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
print(a)
print(b)
resultado= np.concatenate((a,b), axis= 0) 
#concatenar vertical -->axis= 0 (+filas)
#concatenar horizontal --> axis= 1 (+columnas)
print(resultado)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [88]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate((a,b), axis= 1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [90]:
#intersect1d = elementos que son comunes en ambos arrays.
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)


array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [92]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate(
    (a1, a2, ...), 
    axis=0, 
    out=None, 
    dtype=None, 
    casting="same_kind"
)

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [95]:
my_array1= [0,1,2,3,4,5,6,7,8,9,10]
my_array= np.arange(10)
nuevo_array= my_array * 10
primero = nuevo_array[0]
ultimo= nuevo_array[-1]
numeros1_7= nuevo_array[1:8]
print(my_array)
print(nuevo_array)
print(primero)
print(numeros1_7)

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
0
[10 20 30 40 50 60 70]


## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [100]:
my_matrix= np.array([[2,3,4], [2,5,6],[1,4,6]])
print(my_matrix)
        

[[2 3 4]
 [2 5 6]
 [1 4 6]]


## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [102]:
np.arange(1,50,3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [105]:
np.arange(4,1,-0.25)

array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [112]:
#con la funcion ARRAY 

array4x1= np.array([[1],
                    [2],
                    [3],
                    [4]])

#CON LA FUNCION ARANGE
array_4x1 = np.arange(1, 5).reshape(4, 1) #filas, columnas
array_4x1

array([[1],
       [2],
       [3],
       [4]])

In [111]:
array_nuevo= array_4x1.reshape(2,2)
array_nuevo

array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [23]:
aleatorio= np.random.rand(4, 5,3 )  #primero n matrices, n filas y n columnas 
aleatorio
#rand es entre 0-1, sin limites y randint cualquiera hay q ponerle limites 

array([[[0.5630088 , 0.84091357, 0.19476667],
        [0.81435834, 0.89441059, 0.5637553 ],
        [0.81672737, 0.75222519, 0.44237307],
        [0.88186278, 0.17006889, 0.81150549],
        [0.89847857, 0.23849545, 0.93871023]],

       [[0.32378577, 0.66797315, 0.05751242],
        [0.05583369, 0.24556069, 0.51320177],
        [0.26229901, 0.26600494, 0.06729132],
        [0.3338639 , 0.61466341, 0.41536832],
        [0.50542983, 0.27438128, 0.14588597]],

       [[0.96362777, 0.17680027, 0.06370519],
        [0.40194054, 0.68410807, 0.22961893],
        [0.64631425, 0.30185683, 0.24908205],
        [0.2503114 , 0.0330088 , 0.14338606],
        [0.95854469, 0.65696941, 0.57904084]],

       [[0.95836405, 0.77155738, 0.47393734],
        [0.23999271, 0.96439252, 0.18405523],
        [0.44795992, 0.35525144, 0.16550865],
        [0.33119071, 0.55175872, 0.36162389],
        [0.50725928, 0.57819594, 0.54866217]]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [128]:
matriz= np.full((10,1), False)
print(matriz)
matriz1= matriz.reshape(2,5)
matriz1

[[False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]]


array([[False, False, False, False, False],
       [False, False, False, False, False]])

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [25]:
#elementos 5x2x6= 60
#dimensiones = 3 (5 matrices, 2 filas cada matriz, 6 columnas en cada fila)
x= np.random.randint(10,20, size= (5,2,6))
x.size 
x.ndim
x.shape

(5, 2, 6)