![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [1]:
import numpy as np
np.__version__
my_array= np.arange(0,10) #genera un array
my_array[::-2] #da la vuelta y va d 2 en dos 


array([9, 7, 5, 3, 1])

In [17]:
my_array[9:0:-2]


array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [11]:
my_array[7:9][::1]

array([7, 8])

In [32]:
my_array= np.arange(0,10)
my_array[8:6:-1] #ultimo exclusivo

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [38]:
my_array[2:0:-1]


array([2, 1])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [14]:

matrix_x= np.arange(1,21).reshape(4,5)
matrix_x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [58]:
#MATRIZ INVERTIDA 
matriz_invertida= matrix_x[::-1,::-1] #el primero invierte las filas y el segundo las columnas 
matriz_invertida

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [55]:
#ACCEDER A PARTES DE LA MATRIX [USO DE LOS CORCHETES]
#primero filas y despues coma columnas 
#1 fila [0,:]
#2 columna [,:1]
#2 primeras filas y 3 columnas (2x3) [:2, :3]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [59]:

matrix_x[:2,:2]

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [60]:
matrix_x[:5:2,:15:2]

array([[ 1,  3,  5],
       [11, 13, 15]])

In [15]:
matrix_x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [69]:
#3 primeras filas y invertir columnas
matrix_x[:3,::-1] 


array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [68]:
#3 primeras columnas 
matrix_x[:,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [17]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x[0:4:3]

array(['Loro', 'Loro'], dtype='<U5')

In [18]:
x[x== "Loro"]

array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [87]:
secuencia= np.random.randint(0,20 , size= (2, 5,2 )) 
secuencia
#size= 2 matrices 5 filasx 2 columnas

array([[[ 8,  3],
        [ 9,  3],
        [ 7,  0],
        [ 5, 16],
        [18,  3]],

       [[ 5, 17],
        [12,  2],
        [ 8, 10],
        [ 6,  9],
        [ 3,  8]]], dtype=int32)

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [22]:
matrix_x

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [27]:
matrix_x[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [33]:
array1= np.full((10,), 0)
array1
array1.itemsize

8

In [36]:
array1[3]=1 #sustituye el 4 eleemnto por un 1 
array1

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [37]:
vector = np.arange(10,50)
inv_vector= vector[::-1]

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [63]:


y= np.argwhere([[1,2,0,0,4,0]])
#argwhere por defecto te da los indices del array q no sea 0 pero puedes poner otra condicion 
#posiciones donde estan los numeros

np.argwhere([[1,2,0,0,4,0]]).reshape(-1) #aplanarlo, lo haces unidimensional con el reshape -1

array([0, 0, 0, 1, 0, 4])

In [69]:
vector= np.array([1,2,0,0,4,0])
indices = np.nonzero(vector)
indices

(array([0, 1, 4]),)

In [70]:
vector = [1, 2, 0, 0, 4, 0]
indices = []

for i in range(len(vector)): # Genera un rango de índices basado en la longitud del vector.
    if vector[i] != 0: #Verifica si el valor en la posición i no es 0.
        indices.append(i)

print(indices)

[0, 1, 4]


## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [78]:
np.random.rand(10,10).max()


#randint entero, los valores q pongas 
#randn puede ser decimal entre 0 y 1 
#rand entre 0 y 1 exclusivo, entre () pones tamaño


np.float64(0.9932720396020855)

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [81]:
np.random.rand(30).mean()


np.float64(0.5034190462926215)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [87]:
array= np.full((4,4),1)
array[1:-1,1:-1]= 0 #desde la fila 1 hasta la penúltima, y la columna 1 hasta la penúltima
array

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [95]:
a= np.full((8,8),0)
a[1::2, 1::2]= 1


In [92]:
a[::2, ::2] = 0

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [97]:
m= np.random.randint(1,10,(5,5))
media = m.mean()
std= m.std()



In [98]:
(m-media)/std 

array([[ 0.63566083,  1.00523107,  1.00523107, -0.10347967, -1.58176066],
       [-1.21219041, -1.58176066, -1.21219041,  0.63566083,  1.00523107],
       [ 0.63566083, -0.10347967,  0.26609058,  1.37480132, -0.10347967],
       [-1.21219041,  1.37480132,  1.37480132, -0.84262016, -0.10347967],
       [-0.47304992, -1.58176066, -0.84262016,  1.00523107,  0.63566083]])

## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [132]:
secuencia1= np.random.randint(0,10)
array1= np.array(secuencia)
array2 = np.arange(11)
array2

#usamos np.where para condiciones 
arraynuevo= np.where((array2 >=3) & (array2 <=8), -1, array2)


In [101]:
seq= np.arange(0,11)
seq

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
np.where((seq >=3) & (seq <=8), -1, seq)

array([ 0,  1,  2, -1, -1, -1, -1, -1, -1,  9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.